Import Debian version 0.8.4
greylistd (0.8.4) unstable; urgency=low

  * The "Oh this Kingdom is mine!" release
  * I'm declaring myself as maintainer (Closes: #384612)
  * Test for deluser presence before deleting the greylist user (Closes: #431516)
  * Add pt translation (Closes: #436754)
  * Add es translation (Closes: #426173)

diff --git a/debian/postrm b/debian/postrm
--- a/debian/postrm
+++ b/debian/postrm
@@ -33,8 +33,12 @@ case "$1" in
 
 	if id -u greylist >/dev/null 2>&1
 	then
-	    deluser --system greylist
-	    delgroup --system greylist >/dev/null 2>&1 || true
+                if [ -x "$(command -v deluser)" ]; then
+  	            deluser --system greylist
+                    delgroup --system greylist >/dev/null 2>&1 || true
+                else
+                    echo >&2 "not removing greylist system account because deluser command was not found"
+                fi
 	fi
 	;;
 
